### ISSUE TITLE
Separate prefix from command name

### ISSUE THREAD

**Issue by GoelBiju** [nortxort/tinybot#2]
I was wondering if it would be easier to write command if we do not have to check if the command includes the prefix and the command name all the time?

We could try to split the command name from the full string before so we can avoid doing e.g. "if cmd == prefix + 'help'" and instead simply do "if cmd == 'help'".

**Comment by nortxort** [comment]
Personally i don't think its worth it. I mean it's like one extra word to write and ~9 lines to remove it.

```
    if decoded_msg.startswith(prefix):
        if prefix:
            parts = decoded_msg.split(prefix)
            cmd = ''
            cmd_arg = ''
            if len(parts) > 1:
                cmd_parts = parts[1].split(' ')
                cmd = cmd_parts[0].lower().strip()
                cmd_arg = ' '.join(cmd_parts[1:]).strip()
        else:
            parts = decoded_msg.split(' ')
            cmd = parts[0].lower().strip()
            cmd_arg = ' '.join(parts[1:]).strip()
```

**Comment by GoelBiju** [comment]
I thought it could be another way of approaching it, but if it does take more lines to adapt then there is no point. Thanks @nortxort .
